//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Languages.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something wrong happend while adding.. please try again..
        /// </summary>
        public static string AddFailure {
            get {
                return ResourceManager.GetString("AddFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QuestionsBuilder.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic.
        /// </summary>
        public static string ArabicKey {
            get {
                return ResourceManager.GetString("ArabicKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something wrong happend with the application.. please contact administrator.
        /// </summary>
        public static string CodeFailure {
            get {
                return ResourceManager.GetString("CodeFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection string failure.. please try again or change the application settings.
        /// </summary>
        public static string ConnectionStringFailure {
            get {
                return ResourceManager.GetString("ConnectionStringFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current user is not authenticated in the database.. please change the user or contact administrator.
        /// </summary>
        public static string DatabaseAuthenticationError {
            get {
                return ResourceManager.GetString("DatabaseAuthenticationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The connection to the database was denied, please change the current user or contact adminstartor.
        /// </summary>
        public static string DatabaseConnectionDenied {
            get {
                return ResourceManager.GetString("DatabaseConnectionDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The connection to the database was a failure....
        /// </summary>
        public static string DatabaseConnectionFailure {
            get {
                return ResourceManager.GetString("DatabaseConnectionFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something wrong happened with the database.. please contact administrator.
        /// </summary>
        public static string DatabaseError {
            get {
                return ResourceManager.GetString("DatabaseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something wrong happened with the database.. please contact administrator.
        /// </summary>
        public static string DatabaseFailure {
            get {
                return ResourceManager.GetString("DatabaseFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database name.
        /// </summary>
        public static string DatabaseName {
            get {
                return ResourceManager.GetString("DatabaseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The database name can&apos;t be more than 255 charecters in length.
        /// </summary>
        public static string DatabaseNameLength {
            get {
                return ResourceManager.GetString("DatabaseNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The database name can&apos;t be empty.
        /// </summary>
        public static string DatabaseNameRequired {
            get {
                return ResourceManager.GetString("DatabaseNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The executed SQL was incorrect.. please contact administrator.
        /// </summary>
        public static string DatabaseSQLIncorrect {
            get {
                return ResourceManager.GetString("DatabaseSQLIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data source.
        /// </summary>
        public static string DataSource {
            get {
                return ResourceManager.GetString("DataSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data source can&apos;t be more than 255 charecters in length.
        /// </summary>
        public static string DataSourceLength {
            get {
                return ResourceManager.GetString("DataSourceLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data source can&apos;t be empty.
        /// </summary>
        public static string DataSourceRequired {
            get {
                return ResourceManager.GetString("DataSourceRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A general error occured.. please try again or contact administrator.
        /// </summary>
        public static string DefaultResponse {
            get {
                return ResourceManager.GetString("DefaultResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding/Updating failed.. there are empty fields..
        /// </summary>
        public static string EmptyFields {
            get {
                return ResourceManager.GetString("EmptyFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string EnglishKey {
            get {
                return ResourceManager.GetString("EnglishKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while processing your request..
        /// </summary>
        public static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Homepage.
        /// </summary>
        public static string Index {
            get {
                return ResourceManager.GetString("Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to questions.
        /// </summary>
        public static string IndexBack {
            get {
                return ResourceManager.GetString("IndexBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All questions.
        /// </summary>
        public static string IndexHeader {
            get {
                return ResourceManager.GetString("IndexHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication type.
        /// </summary>
        public static string IntegratedSecurity {
            get {
                return ResourceManager.GetString("IntegratedSecurity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The authentication type security can&apos;t be empty.
        /// </summary>
        public static string IntegratedSecurityRequired {
            get {
                return ResourceManager.GetString("IntegratedSecurityRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string LanguageKey {
            get {
                return ResourceManager.GetString("LanguageKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The language can&apos;t be empty.
        /// </summary>
        public static string LanguageRequired {
            get {
                return ResourceManager.GetString("LanguageRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error while fetching the data.. please refresh or try again later.
        /// </summary>
        public static string ListFail {
            get {
                return ResourceManager.GetString("ListFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding/Updating failed.. there is nothing to update..
        /// </summary>
        public static string NothingToUpdate {
            get {
                return ResourceManager.GetString("NothingToUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of smiley faces.
        /// </summary>
        public static string NumberOfSmiley {
            get {
                return ResourceManager.GetString("NumberOfSmiley", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of smiley faces must be in the range of 2 to 5.
        /// </summary>
        public static string NumberOfSmileyRange {
            get {
                return ResourceManager.GetString("NumberOfSmileyRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of smiley faces can&apos;t be empty.
        /// </summary>
        public static string NumberOfSmileyRequired {
            get {
                return ResourceManager.GetString("NumberOfSmileyRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of stars.
        /// </summary>
        public static string NumberOfStar {
            get {
                return ResourceManager.GetString("NumberOfStar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of stars must be in the range of 1 to 10.
        /// </summary>
        public static string NumberOfStarRange {
            get {
                return ResourceManager.GetString("NumberOfStarRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of stars can&apos;t be empty.
        /// </summary>
        public static string NumberOfStarRequired {
            get {
                return ResourceManager.GetString("NumberOfStarRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL server authentication.
        /// </summary>
        public static string OtherKey {
            get {
                return ResourceManager.GetString("OtherKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password can&apos;t be more than 255 charecters in length.
        /// </summary>
        public static string PasswordLength {
            get {
                return ResourceManager.GetString("PasswordLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        public static string Question {
            get {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something wrong happend while adding the question...
        /// </summary>
        public static string QuestionAddFail {
            get {
                return ResourceManager.GetString("QuestionAddFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question added successfully.
        /// </summary>
        public static string QuestionAddSuccess {
            get {
                return ResourceManager.GetString("QuestionAddSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The question was added unsuccessfully, please check the values and make sure they are valid.
        /// </summary>
        public static string QuestionAddValidationFail {
            get {
                return ResourceManager.GetString("QuestionAddValidationFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something wrong happend while fetching the question.. the question is probably deleted.
        /// </summary>
        public static string QuestionDeleted {
            get {
                return ResourceManager.GetString("QuestionDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something wrong happend while deleting the question.. The question might be already deleted.
        /// </summary>
        public static string QuestionDeleteDeleted {
            get {
                return ResourceManager.GetString("QuestionDeleteDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The question was not deleted, something wrong happened in the application, try again!.
        /// </summary>
        public static string QuestionDeletedFail {
            get {
                return ResourceManager.GetString("QuestionDeletedFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The question was removed successfully!.
        /// </summary>
        public static string QuestionDeleteSuccess {
            get {
                return ResourceManager.GetString("QuestionDeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The question was edited unsuccessfully, please check the values and make sure they are valid.
        /// </summary>
        public static string QuestionEditValidationFail {
            get {
                return ResourceManager.GetString("QuestionEditValidationFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End value.
        /// </summary>
        public static string QuestionEndValue {
            get {
                return ResourceManager.GetString("QuestionEndValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End value caption.
        /// </summary>
        public static string QuestionEndValueCaption {
            get {
                return ResourceManager.GetString("QuestionEndValueCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The end value caption can&apos;t be more than 255 charecters in length.
        /// </summary>
        public static string QuestionEndValueCaptionLength {
            get {
                return ResourceManager.GetString("QuestionEndValueCaptionLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The end value caption can&apos;t be empty.
        /// </summary>
        public static string QuestionEndValueCaptionRequired {
            get {
                return ResourceManager.GetString("QuestionEndValueCaptionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The end value must be in the range of 1 to 100.
        /// </summary>
        public static string QuestionEndValueRange {
            get {
                return ResourceManager.GetString("QuestionEndValueRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The end value  can&apos;t be empty.
        /// </summary>
        public static string QuestionEndValueRequired {
            get {
                return ResourceManager.GetString("QuestionEndValueRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something wrong happend while fetching the question.. The question might be deleted.
        /// </summary>
        public static string QuestionFetchDeleted {
            get {
                return ResourceManager.GetString("QuestionFetchDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something wrong happend while fetching the question.. please try again.
        /// </summary>
        public static string QuestionFetchFail {
            get {
                return ResourceManager.GetString("QuestionFetchFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There isn&apos;t a question with that specific id....
        /// </summary>
        public static string QuestionNull {
            get {
                return ResourceManager.GetString("QuestionNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        public static string QuestionOrder {
            get {
                return ResourceManager.GetString("QuestionOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The order must be in the range of 1 to 100.
        /// </summary>
        public static string QuestionOrderLength {
            get {
                return ResourceManager.GetString("QuestionOrderLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The order can&apos;t be empty.
        /// </summary>
        public static string QuestionOrderRequired {
            get {
                return ResourceManager.GetString("QuestionOrderRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The question is out of date.. please refresh to get the latest version of data.
        /// </summary>
        public static string QuestionOutOfDate {
            get {
                return ResourceManager.GetString("QuestionOutOfDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start value.
        /// </summary>
        public static string QuestionStartValue {
            get {
                return ResourceManager.GetString("QuestionStartValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start value caption.
        /// </summary>
        public static string QuestionStartValueCaption {
            get {
                return ResourceManager.GetString("QuestionStartValueCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The start value caption can&apos;t be more than 255 charecters in length.
        /// </summary>
        public static string QuestionStartValueCaptionLength {
            get {
                return ResourceManager.GetString("QuestionStartValueCaptionLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The start value caption can&apos;t be empty.
        /// </summary>
        public static string QuestionStartValueCaptionRequired {
            get {
                return ResourceManager.GetString("QuestionStartValueCaptionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The start value must be in the range of 1 to 100.
        /// </summary>
        public static string QuestionStartValueRange {
            get {
                return ResourceManager.GetString("QuestionStartValueRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The start value can&apos;t be empty.
        /// </summary>
        public static string QuestionStartValueRequired {
            get {
                return ResourceManager.GetString("QuestionStartValueRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string QuestionText {
            get {
                return ResourceManager.GetString("QuestionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text can&apos;t be more than 255 charecters in length.
        /// </summary>
        public static string QuestionTextLength {
            get {
                return ResourceManager.GetString("QuestionTextLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text can&apos;t be empty.
        /// </summary>
        public static string QuestionTextRequired {
            get {
                return ResourceManager.GetString("QuestionTextRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string QuestionType {
            get {
                return ResourceManager.GetString("QuestionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type can&apos;t be empty.
        /// </summary>
        public static string QuestionTypeRequired {
            get {
                return ResourceManager.GetString("QuestionTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something wrong happend while updating the question.. The question probably got deleted.
        /// </summary>
        public static string QuestionUpdateDeleted {
            get {
                return ResourceManager.GetString("QuestionUpdateDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something wrong happend while editing the question...
        /// </summary>
        public static string QuestionUpdateFail {
            get {
                return ResourceManager.GetString("QuestionUpdateFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question updated successfully.
        /// </summary>
        public static string QuestionUpdateSuccess {
            get {
                return ResourceManager.GetString("QuestionUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SaveButton {
            get {
                return ResourceManager.GetString("SaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something wrong happend while saving the settings.. please try again!.
        /// </summary>
        public static string SaveFail {
            get {
                return ResourceManager.GetString("SaveFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The settings were saved successfully!.
        /// </summary>
        public static string SaveSuccess {
            get {
                return ResourceManager.GetString("SaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The connection to the server failed.. please check the server name or contact administrator.
        /// </summary>
        public static string ServerConnectionFailure {
            get {
                return ResourceManager.GetString("ServerConnectionFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The database server is currently down or is not correct.. please check your settings or contact an administrator.
        /// </summary>
        public static string ServerNotFoundOrDown {
            get {
                return ResourceManager.GetString("ServerNotFoundOrDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The database server is currently paused.. please contact administrator.
        /// </summary>
        public static string ServerPaused {
            get {
                return ResourceManager.GetString("ServerPaused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slider.
        /// </summary>
        public static string SliderKey {
            get {
                return ResourceManager.GetString("SliderKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please make sure that the end value is higher than the start value, or they are both 100.
        /// </summary>
        public static string SliderValuesValidationMessage {
            get {
                return ResourceManager.GetString("SliderValuesValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smiley.
        /// </summary>
        public static string SmileyKey {
            get {
                return ResourceManager.GetString("SmileyKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows authentication.
        /// </summary>
        public static string SSPIKey {
            get {
                return ResourceManager.GetString("SSPIKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Star.
        /// </summary>
        public static string StarKey {
            get {
                return ResourceManager.GetString("StarKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test connection.
        /// </summary>
        public static string TestButton {
            get {
                return ResourceManager.GetString("TestButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The connection was unsuccessful, please contact an administrator.
        /// </summary>
        public static string TestFail {
            get {
                return ResourceManager.GetString("TestFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testing connection.. please wait!.
        /// </summary>
        public static string TestingText {
            get {
                return ResourceManager.GetString("TestingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The connection was successful!.
        /// </summary>
        public static string TestSuccess {
            get {
                return ResourceManager.GetString("TestSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question is up to date!.
        /// </summary>
        public static string UpToDate {
            get {
                return ResourceManager.GetString("UpToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The username can&apos;t be more than 255 charecters in length.
        /// </summary>
        public static string UsernameLength {
            get {
                return ResourceManager.GetString("UsernameLength", resourceCulture);
            }
        }
    }
}
